version: "3.9"
services:  
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./demo/:/usr/src/app
      - ./node_modules/:/usr/src/app/node_modules
